export const COUNTRY_CITIES: Record<string, string[]> = {
  "ABŞ": ["New York", "Los Angeles", "Florida", "Chicago", "Miami", "San Francisco"],
  "Almaniya": ["Berlin", "Münhen", "Frankfurt", "Hamburq", "Köln"],
  "Avstraliya": ["Sidney", "Melburn", "Brisben", "Pert", "Adelaida"],
  "Avstriya": ["Vyana", "Zalsburq", "Qrats", "İnsbruk", "Linz"],
  "Andorra": ["Andorra la Vella", "Escaldes-Engordany", "Encamp"],
  "Azərbaycan": ["Bakı", "Gəncə", "Sumqayıt", "Şuşa", "Mingəçevir"],
  "Mərakeş": ["Kasablanka", "Rabat", "Fəz", "Mərakeş", "Tanger"],
  "BƏƏ": ["Dubay", "Əbu-Dabi", "Şarja", "Əl-Ayn", "Əcman"],
  "Böyük Britaniya": ["London", "Mançester", "Birmingem", "Edinburq", "Liverpul"],
  "Belçika": ["Brüssel", "Antverpen", "Gent", "Brugge", "Lyej"],
  "Bolqarıstan": ["Sofiya", "Plovdiv", "Varna", "Burqas", "Ruse"],
  "Braziliya": ["San-Paulu", "Rio de Janeyro", "Brazilia", "Salvador", "Fortaleza"],
  "Cənubi Afrika": ["Keyptaun", "Yohannesburq", "Durban", "Pretoriya", "Port-Elizabet"],
  "Cənubi Koreya": ["Seul", "Busan", "İnçjon", "Daequ", "Qvanju"],
  "Danimarka": ["Kopenhagen", "Orxus", "Odense", "Olborq", "Frederiksberq"],
  "Estoniya": ["Tallin", "Tartu", "Narva", "Parnu", "Kohtla-Yarve"],
  "Finlandiya": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu"],
  "Fransa": ["Paris", "Marsel", "Lion", "Tuluza", "Nitsa"],
  "Gürcüstan": ["Tbilisi", "Batum", "Kutaisi", "Rustavi", "Qori"],
  "Hindistan": ["Nyu Dehli", "Mumbay", "Banqalor", "Heydərabad", "Çennai"],
  "Xorvatiya": ["Zaqreb", "Split", "Riyeka", "Osiyek", "Zadar"],
  "İndoneziya": ["Cakarta", "Surabaya", "Bandunq", "Medan", "Bali"],
  "İraq": ["Bağdad", "Bəsrə", "Mosul", "Ərbil", "Kərkük"],
  "İrlandiya": ["Dublin", "Kork", "Limerik", "Qolvey", "Uoterford"],
  "İslandiya": ["Reykyavik", "Koupavoqür", "Hafnarfyordur", "Akureyri", "Keflavik"],
  "İspaniya": ["Madrid", "Barselona", "Valensiya", "Sevilya", "Malaqa"],
  "İsrail": ["Yerusəlim", "Təl-Əviv", "Hayfa", "Rişon-LeZion", "Petaq-Tikva"],
  "İsveç": ["Stokholm", "Göteborq", "Malmö", "Uppsala", "Västeros"],
  "İsveçrə": ["Sürix", "Cenevrə", "Bazel", "Lozanna", "Bern"],
  "İtaliya": ["Roma", "Milan", "Neapol", "Turin", "Florensiya"],
  "Kipr": ["Nikosiya", "Limasol", "Larnaka", "Pafos", "Famaqusta"],
  "Kanada": ["Toronto", "Vankuver", "Monreal", "Ottava", "Kalkari"],
  "Kolumbiya": ["Boqota", "Medellin", "Kali", "Barrankilya", "Kartaxena"],
  "Litva": ["Vilnüs", "Kaunas", "Klaypeda", "Şyaulyay", "Panevejis"],
  "Latviya": ["Riqa", "Dauqavpils", "Liepaya", "Yelqava", "Yurmala"],
  "Macarıstan": ["Budapeşt", "Debretsen", "Mişkols", "Seqed", "Peç"],
  "Malayziya": ["Kuala-Lumpur", "Penanq", "Johor-Baxru", "Melaka", "İpoh"],
  "Meksika": ["Meksiko", "Monteri", "Quadalahara", "Puebla", "Tihuana"],
  "Mısir": ["Qahirə", "İsgəndəriyyə", "Qiza", "Şarm-əl-Şeyx", "Lüksor"],
  "Niderland": ["Amsterdam", "Rotterdam", "Haaqa", "Utrext", "Eindhoven"],
  "Norveç": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Sandnes"],
  "Polşa": ["Varşava", "Krakov", "Lodz", "Vrotslav", "Poznan"],
  "Portuqaliya": ["Lissabon", "Porto", "Amadora", "Braqa", "Koimbra"],
  "Rumıniya": ["Buxarest", "Kluj-Napoka", "Timişoara", "Yassı", "Konstanta"],
  "Slovakiya": ["Bratislava", "Koşitse", "Preshov", "Jilina", "Nitra"],
  "Sloveniya": ["Lyublyana", "Maribor", "Selye", "Kran", "Koper"],
  "Tailand": ["Banqkok", "Nontaburi", "Pattaya", "Puket", "Çianq May"],
  "Türkiyə": ["İstanbul", "Ankara", "İzmir", "Antalya", "Bursa"],
  "Vyetnam": ["Hoşimin", "Hanoy", "Da Nanq", "Hai-Fonq", "Nha-Trang"],
  "Yaponiya": ["Tokio", "Osaka", "Kioto", "Yokoqama", "Sapporo"],
  "Yunanıstan": ["Afina", "Saloniki", "Patras", "İraklion", "Larissa"],
  "Çexiya": ["Praqa", "Brno", "Ostrava", "Plzen", "Libereç"],
  "Çin": ["Pekin", "Şanxay", "Şenjen", "Quançjou", "Çendu"]
};

// Auto extract strictly to UNIQUE_COUNTRIES to maintain absolute code backward compatibility
export const UNIQUE_COUNTRIES = Object.keys(COUNTRY_CITIES).sort();
