export const COUNTRY_CITIES: Record<string, string[]> = {
  "USA": ["New York", "Los Angeles", "Florida", "Chicago", "Miami", "San Francisco"],
  "Germany": ["Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  "Austria": ["Vienna", "Salzburg", "Graz", "Innsbruck", "Linz"],
  "Andorra": ["Andorra la Vella", "Escaldes-Engordany", "Encamp"],
  "Azerbaijan": ["Baku", "Ganja", "Sumqayit", "Shusha", "Mingachevir"],
  "Morocco": ["Casablanca", "Rabat", "Fez", "Marrakech", "Tangier"],
  "UAE": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman"],
  "UK": ["London", "Manchester", "Birmingham", "Edinburgh", "Liverpool"],
  "Belgium": ["Brussels", "Antwerp", "Ghent", "Bruges", "Liege"],
  "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"],
  "Brazil": ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Fortaleza"],
  "South_Africa": ["Cape Town", "Johannesburg", "Durban", "Pretoria", "Port Elizabeth"],
  "South_Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Gwangju"],
  "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Frederiksberg"],
  "Estonia": ["Tallinn", "Tartu", "Narva", "Parnu", "Kohtla-Jarve"],
  "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu"],
  "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"],
  "Georgia": ["Tbilisi", "Batumi", "Kutaisi", "Rustavi", "Gori"],
  "India": ["New Delhi", "Mumbai", "Bangalore", "Hyderabad", "Chennai"],
  "Croatia": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar"],
  "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Medan", "Bali"],
  "Iraq": ["Baghdad", "Basra", "Mosul", "Erbil", "Kirkuk"],
  "Ireland": ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  "Iceland": ["Reykjavik", "Kopavogur", "Hafnarfjordur", "Akureyri", "Keflavik"],
  "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Malaga"],
  "Israel": ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva"],
  "Sweden": ["Stockholm", "Gothenburg", "Malmo", "Uppsala", "Vasteras"],
  "Switzerland": ["Zurich", "Geneva", "Basel", "Lausanne", "Bern"],
  "Italy": ["Rome", "Milan", "Naples", "Turin", "Florence"],
  "Cyprus": ["Nicosia", "Limassol", "Larnaca", "Paphos", "Famagusta"],
  "Canada": ["Toronto", "Vancouver", "Montreal", "Ottawa", "Calgary"],
  "Colombia": ["Bogota", "Medellin", "Cali", "Barranquilla", "Cartagena"],
  "Lithuania": ["Vilnius", "Kaunas", "Klaipeda", "Siauliai", "Panevezys"],
  "Latvia": ["Riga", "Daugavpils", "Liepaja", "Jelgava", "Jurmala"],
  "Hungary": ["Budapest", "Debrecen", "Miskolc", "Szeged", "Pecs"],
  "Malaysia": ["Kuala Lumpur", "Penang", "Johor Bahru", "Melaka", "Ipoh"],
  "Mexico": ["Mexico City", "Monterrey", "Guadalajara", "Puebla", "Tijuana"],
  "Egypt": ["Cairo", "Alexandria", "Giza", "Sharm el-Sheikh", "Luxor"],
  "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  "Norway": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Sandnes"],
  "Poland": ["Warsaw", "Krakow", "Lodz", "Wroclaw", "Poznan"],
  "Portugal": ["Lisbon", "Porto", "Amadora", "Braga", "Coimbra"],
  "Romania": ["Bucharest", "Cluj-Napoca", "Timisoara", "Iasi", "Constanta"],
  "Slovakia": ["Bratislava", "Kosice", "Presov", "Zilina", "Nitra"],
  "Slovenia": ["Ljubljana", "Maribor", "Celje", "Kranj", "Koper"],
  "Thailand": ["Bangkok", "Nonthaburi", "Pattaya", "Phuket", "Chiang Mai"],
  "Turkey": ["Istanbul", "Ankara", "Izmir", "Antalya", "Bursa"],
  "Vietnam": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Nha Trang"],
  "Japan": ["Tokyo", "Osaka", "Kyoto", "Yokohama", "Sapporo"],
  "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"],
  "Czech_Republic": ["Prague", "Brno", "Ostrava", "Plzen", "Liberec"],
  "China": ["Beijing", "Shanghai", "Shenzhen", "Guangzhou", "Chengdu"]
};

export const COUNTRY_FLAGS: Record<string, string> = {
  "USA": "/flags/us.svg",
  "Germany": "/flags/de.svg", 
  "Australia": "/flags/au.svg",
  "Austria": "🇦🇹",
  "Andorra": "🇦🇩",
  "Azerbaijan": "🇦🇿",
  "Morocco": "🇲🇦",
  "UAE": "/flags/ae.svg",
  "UK": "/flags/gb.svg",
  "Belgium": "🇧🇪",
  "Bulgaria": "🇧🇬",
  "Brazil": "🇧🇷",
  "South_Africa": "🇿🇦",
  "South_Korea": "🇰🇷",
  "Denmark": "🇩🇰",
  "Estonia": "🇪🇪",
  "Finland": "🇫🇮",
  "France": "🇫🇷",
  "Georgia": "🇬🇪",
  "India": "🇮🇳",
  "Croatia": "🇭🇷",
  "Indonesia": "🇮🇩",
  "Iraq": "🇮🇶",
  "Ireland": "🇮🇪",
  "Iceland": "🇮🇸",
  "Spain": "🇪🇸",
  "Israel": "🇮🇱",
  "Sweden": "🇸🇪",
  "Switzerland": "/flags/ch.svg",
  "Italy": "/flags/it.svg",
  "Cyprus": "🇨🇾",
  "Canada": "🇨🇦",
  "Colombia": "🇨🇴",
  "Lithuania": "🇱🇹",
  "Latvia": "🇱🇻",
  "Hungary": "🇭🇺",
  "Malaysia": "🇲🇾",
  "Mexico": "🇲🇽",
  "Egypt": "🇪🇬",
  "Netherlands": "🇳🇱",
  "Norway": "🇳🇴",
  "Poland": "🇵🇱",
  "Portugal": "🇵🇹",
  "Romania": "🇷🇴",
  "Slovakia": "🇸🇰",
  "Slovenia": "🇸🇮",
  "Thailand": "🇹🇭",
  "Turkey": "🇹🇷",
  "Vietnam": "🇻🇳",
  "Japan": "/flags/jp.svg",
  "Greece": "🇬🇷",
  "Czech_Republic": "🇨🇿",
  "China": "🇨🇳",
  "Monaco": "🇲🇨"
};

export const UNIQUE_COUNTRIES = Object.keys(COUNTRY_CITIES).sort();
